[tool.poetry]
name = "a-toad-emo"
version = "0.1.0"
description = ""
authors = ["BlancJH"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
